
version: '3'

services:
  backend:
    restart: unless-stopped
    build:
      context: ./blog_backend
      args:
        DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DJANGO_CORS_ORIGIN_WHITELIST: $DJANGO_CORS_ORIGIN_WHITELIST
    command: gunicorn blog_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/var/django_static
  frontend:
    build:
      context: ./blog_frontend
      args:
        API_URL: $API_URL
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:8080
      - 433:433
    volumes:
      - ./webserver/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
      - static_volume:/backend/var/django_static
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  static_volume:
  build_folder: